// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using historiasClinicas.Models;
using System.Threading.Tasks;

namespace historiasClinicas.Migrations
{
    [DbContext(typeof(historiasClinicasContext))]
    partial class historiasClinicasContextModelSnapshot : ModelSnapshot
    {   
        public DbSet<InternacPaciente> InternacPacientes { get; set; }
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("historiasClinicas.Models.InternacPaciente", b =>
                {
                    b.Property<int>("Id_internacion")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Fecha_ingreso");

                    b.Property<int>("HistoriaClinicaGral");

                    b.Property<int>("Id_expediente");

                    b.Property<int>("Id_personal");

                    b.Property<string>("Imp_diagnostica");

                    b.Property<string>("Tratamiento");

                    b.HasKey("Id_internacion");

                    b.ToTable("InternacPaciente");
                });
#pragma warning restore 612, 618
        }

        internal Task SaveChangesAsync()
        {
            throw new NotImplementedException();
        }

        internal object Entry(InternacPaciente item)
        {
            throw new NotImplementedException();
        }
    }
}
